version: '3'

services:

  web:
    labels:
      shipyard.route: '/'
    build: '.'
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: 'flask_app'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  db1:
    image: mdillon/postgis
    environment:
        POSTGRES_DB: ephemeral
        POSTGRES_PASSWORD: password
    volumes:
        - "db1:/var/lib/postgresql/data/"
    ports:
        - 5432

  db2:
    image: mdillon/postgis
    environment:
        POSTGRES_DB: ephemeral
        POSTGRES_PASSWORD: password
    volumes:
        - "db2:/var/lib/postgresql/data/"
    ports:
        - 5432

  redis:
    image: 'redis:4-alpine'

volumes:
  postgres:
  db1:
  db2:
