version: '3'

services:

  web:
    build: '.'
    ports:
      - '8080:8080'

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: 'flask_app'

  redis:
    image: 'redis:4-alpine'
