version: '3'

services:

  web:
    labels:
      shipyard.route: '/'
    build: '.'
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: 'flask_app'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:4-alpine'

  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmqdata:/bitnami'

volumes:
  postgres:
  rabbitmqdata:
