version: '3'

services:

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: 'flask_app'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:4-alpine'

  web:
    labels:
      shipyard.route: '/'
    build: '.'
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'

volumes:
  postgres:
